### ISSUE TITLE
bad module name

### ISSUE THREAD

**Issue by slavkoja** [proftpd/www.proftpd.org#8]
On the [ProFTPD Contrib Module Documentation](http://www.proftpd.org/docs/contrib/index.html) pahe, is ``mod_ban`` listed twice, but the first seems to be a mistake:

> The mod_ban module
>     For supporting HOTP/TOTP One-Time Passwords (OTP) for multi-factor authentication, e.g. using Google Authenticator 
> 
> The mod_ban module
>     For supporting automatic bans based on configurable thresholds 

The links seems OK

**Comment by Castaglia** [comment]
Thanks!  I've just pushed a fix for the copy/paste error; it should propagate out to the website shortly.

**Comment by slavkoja** [comment]
Yes, it seems fixed now
